### PR TITLE
First attempt to rpathify the mpir binary

### PR DESCRIPTION
**Pull request by rhc54**
Signed-off-by: Ralph Castain <rhc@pmix.org>

### CODE REVIEW

**Comment by rhc54** [comment]
@ggouaillardet I don't think this is doing quite what we want, but it doesn't seem to be doing any harm either. If you get a chance, can you take a peek and see what you think?

**Comment by jdelsign** [comment]
One other related related to the "configure" script... It doesn't seem to support "--enable-debug" like PRRTE, OMPI, and OpenPMIx do. The work around is easy:
```
env CXXFLAGS=-g ... .../configure ...
```
But it would be nice if the shim supported it too.

**Comment by rhc54** [comment]
I fixed the "--enable-debug" one

**Comment by jdelsign** [comment]
I don't need the change to set RPATH anymore. When I build the MPIR shim for inclusion with TotalView, I'm setting up the RPATH (via configure LDFLAGS) to be exactly what I want for both Linux and Mac OS X. So if it's all the same to everyone else, I'd prefer it if RPATH was not automatically added when the shim is built.

**Comment by rhc54** [comment]
No issues - if someone needs it later, we can always enable it with a configure option

**Pull request closed without merging**
