### PR TITLE
Some final cleanups to enable compile/install

### PR DESCRIPTION
**Pull request by rhc54**
Add the src/Makefile.am. Save the CPPFLAGS and friends and add them in
the Makefile.am instead of modifying the upper-level versions.

Signed-off-by: Ralph Castain <rhc@pmix.org>

### CODE REVIEW

**Comment by rhc54** [comment]
I give up - something is broken in the webhooks that is preventing the checkers from updating the status. All is good here.

**Comment by jdelsign** [comment]
Cool, we're getting much closer...
```
mic:/amd/home/jdelsign/src/tools-external/mpir-shim.master-microway3/build>make
Making all in src
make[1]: Entering directory `/amd/home/jdelsign/src/tools-external/mpir-shim.master-microway3/build/src'
  CXX      mpir-mpir.o
In file included from ../../../mpir-shim.master/src/mpir.cxx:83:0:
../src/include/mpirshim_config.h:21:33: fatal error: mpirshim_config_top.h: No such file or directory
 #include "mpirshim_config_top.h"
                                 ^
compilation terminated.
make[1]: *** [mpir-mpir.o] Error 1
make[1]: Leaving directory `/amd/home/jdelsign/src/tools-external/mpir-shim.master-microway3/build/src'
make: *** [all-recursive] Error 1
mic:/amd/home/jdelsign/src/tools-external/mpir-shim.master-microway3/build>ls src/include/
mpirshim_config.h  stamp-h1  version.h
mic:/amd/home/jdelsign/src/tools-external/mpir-shim.master-microway3/build>
```

This stuff is all Greek to me, but it appears as if the mpirshim_config_top.h and mpirshim_config_bottom.h headers are not getting setup properly.

**Comment by rhc54** [comment]
Err? Those files are in the repo - they don't get created. I did a fresh clone and they are definitely present - everything configured/built just fine.
```text
./autogen.sh && ./configure --with-pmix=/Users/rhc/pmix/build/clean --prefix=/Users/rhc/pmix/build/mpirshim
...lots of output
$ make install
Making install in src
  CXX      mpir-mpir.o
  CXXLD    mpir
 /opt/local/bin/gmkdir -p '/Users/rhc/pmix/build/mpirshim/bin'
  /opt/local/bin/ginstall -c mpir '/Users/rhc/pmix/build/mpirshim/bin'
make[2]: Nothing to be done for `install-data-am'.
make[2]: Nothing to be done for `install-exec-am'.
make[2]: Nothing to be done for `install-data-am'.
$
````

**Comment by jdelsign** [comment]
Hmmm... Weird. I'll start fresh to see if I'm getting bitten by something cached.

**Comment by jdelsign** [comment]
Nope, starting fresh did not help. I did the following to clone it:
```
cd /home/jdelsign/src/tools-external
git clone ssh://git@github.com/openpmix/mpir-shim.git mpir-shim.master
```
Then:
```
./autogen.sh
```
Then in a build hierarchy:
```
../../mpir-shim.master/configure \
  --prefix=$HOME/src/tools-external/mpir-shim.master-microway3/install \
  --with-pmix=$HOME/src/tools-external/openpmix-microway3/install
make
```
The compile failed the same way.

**Comment by rhc54** [comment]
are the files present in src/include?

**Comment by jdelsign** [comment]
Yes, they are in the cloned hierarchy:
```
lid:/amd/home/jdelsign/src/tools-external/mpir-shim/src/include>ls -l
total 40
-rw-r--r-- 1 jdelsign tss 12412 Mar  6 16:05 mpirshim_config.h.in
-rw-r--r-- 1 jdelsign tss 12695 Mar  6 16:05 mpirshim_config_bottom.h
-rw-r--r-- 1 jdelsign tss  1370 Mar  6 16:05 mpirshim_config_top.h
-rw-r--r-- 1 jdelsign tss  1562 Mar  6 16:05 version.h.in
lid:/amd/home/jdelsign/src/tools-external/mpir-shim/src/include>
```
But they are not in the build hierarchy after running configure:
```
mic:/amd/home/jdelsign/src/tools-external/mpir-shim.master-microway3/build>ls -l src/include/
total 24
-rw-r--r-- 1 jdelsign tss 16375 Mar 11 13:18 mpirshim_config.h
-rw-r--r-- 1 jdelsign tss    44 Mar 11 13:18 stamp-h1
-rw-r--r-- 1 jdelsign tss  1562 Mar 11 13:18 version.h
mic:/amd/home/jdelsign/src/tools-external/mpir-shim.master-microway3/build>
```
What's supposed to happen here? Is configure supposed to copy them to the build hierarchy, or is the Makefile supposed to add a "-I<source-hierachy>" to CXX compile command?

**Comment by rhc54** [comment]
Ah - I just realized you are doing a VPATH build. This is likely the problem. I'll try to fix it

**Comment by jdelsign** [comment]
Great thanks... I'll have to learn how automake works one of these days.

**Pull request merged**
