### PR TITLE
Add VPATH support

### PR DESCRIPTION
**Pull request by rhc54**
Ensure we set the flags correctly

Signed-off-by: Ralph Castain <rhc@pmix.org>

### CODE REVIEW

**Comment by rhc54** [comment]
Sigh - the webhooks are totally busted.

**Comment by jdelsign** [comment]
Thanks, we're getting closer. It builds OK, but it's not setting DT_RPATH or DT_RUNPATH in the .dynamic section, so it can't find libpmix.so.0 on its own:
```
mic:/amd/home/jdelsign/src/tools-external/mpir-shim.master-microway3/build>make
Making all in src
make[1]: Entering directory `/amd/home/jdelsign/src/tools-external/mpir-shim.master-microway3/build/src'
  CXX      mpir-mpir.o
  CXXLD    mpir
make[1]: Leaving directory `/amd/home/jdelsign/src/tools-external/mpir-shim.master-microway3/build/src'
make[1]: Entering directory `/amd/home/jdelsign/src/tools-external/mpir-shim.master-microway3/build'
make[1]: Nothing to be done for `all-am'.
make[1]: Leaving directory `/amd/home/jdelsign/src/tools-external/mpir-shim.master-microway3/build'
mic:/amd/home/jdelsign/src/tools-external/mpir-shim.master-microway3/build>src/mpir
src/mpir: error while loading shared libraries: libpmix.so.0: cannot open shared object file: No such file or directory
mic:/amd/home/jdelsign/src/tools-external/mpir-shim.master-microway3/build>readelf -d src/mpir|grep PATH
mic:/amd/home/jdelsign/src/tools-external/mpir-shim.master-microway3/build>          
```

**Comment by rhc54** [comment]
I'm afraid that is outside my expertise - I always just set `LD_LIBRARY_PATH`. If someone else knows how to do what you are asking about, then perhaps they can contribute it?

**Comment by jdelsign** [comment]
prun gets it set correctly, so the secret is probably buried in ompi/prrte's configury:
```
% readelf -d `which prun` | grep PATH
 0x000000000000000f (RPATH)              Library rpath: [/home/jdelsign/src/tools-external/ompi-microway3/install/lib]
% 
```
Normally, I pass something like "-Wl,-R<path>" to the linker. automake probably has a fancy (portable) way of doing that.

**Comment by jdelsign** [comment]
I looked at the "RPATHIFY" stuff that PRRTE does, and it seemed like a much bigger chunk of automake code than I'd be comfortable trying to add to the shim.

However, I can get what I want as follows:
```
env LDFLAGS="-Wl,-R,<path-pmix-install>/lib" .../configure ...
```

I've been conditioned over the years to try to avoid setting LD_LIBRARY_PATH, because it has always causes trouble. Inevitably, I end up picking up the wrong library. The RPATH stuff is nice because it sticks to the executable without having a broader effect.

**Comment by rhc54** [comment]
Okay, I can work that into the configury - thx!

**Pull request merged**
