### PR TITLE
Convert mpir to C and add a shared library

### PR DESCRIPTION
**Pull request by jjhursey**
* Convert `mpir` from C++ to C to better match OpenPMIx and other
   debugger examples.
   - `mpir` staticly links against the `libmpirshim.a` library
 * Add a shared and static library version of the MPIR Shim
   - This allows launchers to embed the MPIR Shim without requiring
     the user to use the `mpir` command.
 * Add an 'attach mode' option to `mpir` that allows for attaching
   to a running job through the `mpir` interface.
 * Extend documentation

### CODE REVIEW

**Comment by jjhursey** [comment]
This is missing one option that was documented in the C++ version: `--pmix-prefix PATH` [here](https://github.com/openpmix/mpir-shim/blob/master/src/mpir.cxx#L885)

I will add that functionality back into this version before marking it ready for full review. Everything else in this PR is complete and ready for review though - so feel free to take a look at let us know what you think.

**Comment by jjhursey** [comment]
Latest push contains the `--pmix-prefix PATH` support. This is now ready for review.

**Comment by jjhursey** [comment]
@jdelsign Will you be able to give this branch a try before we commit? I'd like to make sure it still works as expected with your product and prrte. We can fix things up after the merge, but I would prefer to handle them here if we can.

**Comment by jdelsign** [comment]
> @jdelsign Will you be able to give this branch a try before we commit? I'd like to make sure it still works as expected with your product and prrte. We can fix things up after the merge, but I would prefer to handle them here if we can.

@jjhursey I guess that depends on when you need it and whether or not I have to update OpenPMIx, libevent, and/or libhwloc. If it's just the shim, I can try to nudge it along in the next couple of day. Anything bigger than that will take longer.

BTW, IMHO, the conversion from C++ to C seems like a step in the wrong direction. I found that using the C API was error prone, especially in the area of allocating and initializing vectors of objects to pass into the PMIx function. The C++ wrappers alleviated a lot of pain in that area. Given that the shim was an application, not a library, I thought using C++ was OK. But even if we did want to package the shim functionality as a library, it could still be implemented in C++ but export a C API. Water over the dam I suppose.

**Comment by jjhursey** [comment]
It probably needs the latest OpenPMIx and PRRTE to run properly. I fixed a couple of issues in PRRTE as we developed it. Otherwise, it should be the same build/run process as before.

As far as moving to C. I understand your comment about C++, and indeed there were some aspects of the C++ that just could not be easily replicated in C (entry/exit markers for example). The move to C was more to make the MPIR Shim yet another example code for PMIx tools integration. So we tried to match the style and some of the flow of the [prrte/examples/debugger](https://github.com/openpmix/prrte/tree/master/examples/debugger) examples.

That way a tool could use the MPIR Shim for the near term and then use the MPIR Shim library code as an example (even copy/paste out of it if necessary) of how they might access the same information directly from PMIx without the MPIR Shim in the future.

**Comment by jdelsign** [comment]
@jjhursey I'll add comments here as I go.

I ran autogen.sh and autoconf seems unhappy about something. I'm not sure if this is expected/normal or not, but it's new behavior.

% ./autogen.sh
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I ./config
configure.ac:448: warning: AC_REQUIRE: `AC_PROG_CXX' was expanded before it was required
configure.ac:448: http://www.gnu.org/software/autoconf/manual/autoconf.html#Expanded-Before-Required
../../lib/autoconf/c.m4:667: AC_LANG_COMPILER(C++) is expanded from...
../../lib/autoconf/lang.m4:329: AC_LANG_COMPILER_REQUIRE is expanded from...
../../lib/autoconf/general.m4:2678: AC_LINK_IFELSE is expanded from...
../../lib/m4sugar/m4sh.m4:639: AS_IF is expanded from...
../../lib/autoconf/general.m4:2031: AC_CACHE_VAL is expanded from...
/usr/share/aclocal/libtool.m4:1130: _LT_SYS_MODULE_PATH_AIX is expanded from...
/usr/share/aclocal/libtool.m4:5822: _LT_LANG_CXX_CONFIG is expanded from...
/usr/share/aclocal/libtool.m4:819: _LT_LANG is expanded from...
/usr/share/aclocal/libtool.m4:801: LT_LANG is expanded from...
config/mpirshim_setup_cxx.m4:34: MPIRSHIM_PROG_CXX is expanded from...
config/mpirshim_setup_cxx.m4:67: _MPIRSHIM_SETUP_CXX_COMPILER is expanded from...
config/mpirshim_setup_cxx.m4:47: MPIRSHIM_SETUP_CXX is expanded from...
configure.ac:448: the top level
...repeated several times...

**Comment by rhc54** [comment]
Suggestion: why don't we retain the C++ version as well as the new C version? Just put each in their own directory and they should co-exist just fine. One could then build/use whichever version one wanted.

**Comment by jdelsign** [comment]
@jjhursey OK, first problem is that the main() from the original C++ version of the code lost the comments intended for the user. Basically, in a manner similar to orterun, the mpir executable is intended to be started under the debugger, and the comments in/above main() give the user a hint as to what is going on... Here is how it used to read:

``
/***********************************************************************/
/*
 * A PMIx to MPIR shim program that extracts PMIx proctable information
 * from a PMIx launcher process (prun, mpirun, etc.) and uses it to
 * implement the MPIR specification.
 *
 * Used with OpenPMIx or Open MPI v5 and later in conjunction with
 * legacy versions of tools that support MPIR only, for example:
 *
 *   totalview -args mpir mpirun -n 32 mpi-program
 *
 * TotalView treats "mpir" as an MPI starter program because it contains
 * the MPIR symbols.  When "mpir" starts running, it uses PMIx to launch
 * "mpirun", which in turn will launch the "mpi-program".  When "mpir"
 * receives the program-launch PMIx event, it extracts the process table
 * from PMIx, fills in the MPIR_proctable[], and calls MPIR_breakpoint.
 * When "mpir" hits the MPIR_breakpoint, TotalView extracts the MPI
 * process information from the MPIR_proctable[] and attaches to the
 * processes in the job.
 *
 * See: https://github.com/openpmix/mpir-shim
 */
/***********************************************************************/

int main (int argc, char **argv)
{
  /*
   * If you are seeing this comment under a debugger,
   * run this process to launch your MPI application.
   */
  return mpir (argc, argv);
}  /* main */
``

**Comment by jdelsign** [comment]
I built just the shim, and ran it with a version of OMPI and OpenPMIx master from May (~ 2 months ago). The shim hangs when I run it with "mpirun". See below.

If I start a DVM using prte and run the job using prun instead of mpirun, the shim seems to work OK.

Here's the debug output of the hang:
```
mic:/amd/home/jdelsign/PMIx>~/src/tools-external/mpir-shim.jjhursey-microway3/export/bin/mpir -d mpirun -n 3 --map-by node -x MESSAGE=name --hostfile myhostfile tx_basic_mpi
DEBUG: <<< EXIT  (process_options): 
DEBUG: Launcher 'mpir', performing a proxy run
DEBUG: >>> ENTER (setup_signal_handlers): 
DEBUG: <<< EXIT  (setup_signal_handlers): 
DEBUG: >>> ENTER (initialize_as_tool): 
DEBUG: Requested Tool namespace of 'mpir.44071'
DEBUG: Tool namespace='mpir.44071', rank=0
DEBUG: <<< EXIT  (initialize_as_tool): 
DEBUG: >>> ENTER (setup_session_directory): 
DEBUG: session directory is /tmp/mpir.session.14694.44071
DEBUG: rendezvoud file is /tmp/mpir.session.14694.44071/mpir.rndz.44071
DEBUG: <<< EXIT  (setup_session_directory): 
DEBUG: >>> ENTER (register_default_event_handler): 
DEBUG: >>> ENTER (wait_for_condition): Condition 'callback-registration'
DEBUG: Wait for condition callback-registration to be posted
DEBUG: >>> ENTER (registration_complete_handler): Status 'SUCCESS'
DEBUG: >>> ENTER (post_condition): Condition 'callback-registration'
DEBUG: <<< EXIT  (post_condition): 
DEBUG: <<< EXIT  (wait_for_condition): Condition 'callback-registration'
DEBUG: <<< EXIT  (register_default_event_handler): 
DEBUG: >>> ENTER (spawn_launcher_and_application): 
DEBUG: <<< EXIT  (registration_complete_handler): String 'default-callback'
DEBUG: Calling PMIx_Spawn for mpirun
DEBUG: PMIx_Spawn status SUCCESS launcher_namespace: mpir.44071.1
DEBUG: <<< EXIT  (spawn_launcher_and_application): 
DEBUG: >>> ENTER (connect_to_server): 
DEBUG: In connect_to_server, rendezvous_file=/tmp/mpir.session.14694.44071/mpir.rndz.44071
DEBUG: >>> ENTER (query_launcher_namespace): 
DEBUG: <<< EXIT  (query_launcher_namespace): Connected to launcher nspace '' rank -2
DEBUG: <<< EXIT  (connect_to_server): Connected to launcher nspace '' rank -2
DEBUG: >>> ENTER (register_launcher_ready_handler): 
DEBUG: >>> ENTER (wait_for_condition): Condition 'callback-registration'
DEBUG: Wait for condition callback-registration to be posted
DEBUG: >>> ENTER (launcher_ready_handler): Event 'LAUNCHER-READY', nspace 'mpir.44071', rank '0'
DEBUG: >>> ENTER (post_condition): Condition 'launch-ready'
DEBUG: <<< EXIT  (post_condition): 
DEBUG: <<< EXIT  (launcher_ready_handler): 
DEBUG: >>> ENTER (registration_complete_handler): Status 'SUCCESS'
DEBUG: >>> ENTER (post_condition): Condition 'callback-registration'
DEBUG: <<< EXIT  (post_condition): 
DEBUG: <<< EXIT  (registration_complete_handler): String 'launcher-ready-callback'
DEBUG: <<< EXIT  (wait_for_condition): Condition 'callback-registration'
DEBUG: <<< EXIT  (register_launcher_ready_handler): 
DEBUG: >>> ENTER (register_launcher_complete_handler): 
DEBUG: >>> ENTER (wait_for_condition): Condition 'callback-registration'
DEBUG: Wait for condition callback-registration to be posted
DEBUG: >>> ENTER (registration_complete_handler): Status 'SUCCESS'
DEBUG: >>> ENTER (post_condition): Condition 'callback-registration'
DEBUG: <<< EXIT  (post_condition): 
DEBUG: <<< EXIT  (registration_complete_handler): String 'launcher-complete-callback'
DEBUG: <<< EXIT  (wait_for_condition): Condition 'callback-registration'
DEBUG: <<< EXIT  (register_launcher_complete_handler): 
DEBUG: Waiting for launcher to become ready
DEBUG: >>> ENTER (wait_for_condition): Condition 'launch-ready'
DEBUG: <<< EXIT  (wait_for_condition): Condition 'launch-ready'
DEBUG: Launcher is ready
DEBUG: >>> ENTER (register_launcher_terminate_handler): 
DEBUG: >>> ENTER (wait_for_condition): Condition 'callback-registration'
DEBUG: Wait for condition callback-registration to be posted
DEBUG: >>> ENTER (registration_complete_handler): Status 'SUCCESS'
DEBUG: >>> ENTER (post_condition): Condition 'callback-registration'
DEBUG: <<< EXIT  (post_condition): 
DEBUG: <<< EXIT  (registration_complete_handler): String 'launcher-terminate-callback'
DEBUG: <<< EXIT  (wait_for_condition): Condition 'callback-registration'
DEBUG: <<< EXIT  (register_launcher_terminate_handler): 
DEBUG: >>> ENTER (send_launch_directives): Namespace '', rank -2
DEBUG: <<< EXIT  (send_launch_directives): 
DEBUG: Wait for launch to complete
DEBUG: >>> ENTER (wait_for_condition): Condition 'launch_complete'
DEBUG: Wait for condition launch_complete to be posted
...HANG...
```

And here is the backtraces of the mpir threads:
```
d1.<> st
1        (48897)      Stopped     [/home/jdelsign/src/tools-external/mpir-shim.jjhursey-microway3/export/bin/mpir]
  1.1    (48897/0x7f0e05db7740)   Stopped     PC=0x7f0e03d7b965
  1.3    (48897/0x7f0dff420700)   Stopped     PC=0x7f0e03a980f3
  1.4    (48897/0x7f0e0085f700)   Stopped     PC=0x7f0e03aa1603
d1.<> f p w
Thread 1.1:
>  0 pthread_cond_wait PC=0x7f0e03d7b965, FP=0x7ffd7e279000 [/lib64/libpthread.so.0]
   1 wait_for_condition PC=0x0040412a, FP=0x7ffd7e279020 [/home/jdelsign/src/tools-external/mpir-shim.jjhursey/src/mpirshim.c#868]
   2 MPIR_Shim_common PC=0x00407c8b, FP=0x7ffd7e279050 [/home/jdelsign/src/tools-external/mpir-shim.jjhursey/src/mpirshim.c#2159]
   3 main             PC=0x00401fac, FP=0x7ffd7e2790a0 [/home/jdelsign/src/tools-external/mpir-shim.jjhursey/src/mpir.c#212]
   4 __libc_start_main PC=0x7f0e039c5493, FP=0x7ffd7e279160 [/lib64/libc.so.6]
   5 _start           PC=0x00401ae4, FP=0x7ffd7e279168 [/amd/home/jdelsign/src/tools-external/mpir-shim.jjhursey-microway3/export/bin/mpir]
Thread 1.3:
>  0 __select_nocancel PC=0x7f0e03a980f3, FP=0x7f0dff41fe00 [/lib64/libc.so.6]
   1 listen_thread    PC=0x7f0e05965723, FP=0x7f0dff41ff10 [/home/jdelsign/tvbld/linux-x86-64/microway3/totalview.develop/3rdparty/openpmix/OpenPMIx/src/mca/ptl/base/ptl_base_listener.c#214]
   2 start_thread     PC=0x7f0e03d77dce, FP=0x7f0dff41ffb0 [/lib64/libpthread.so.0]
   3 __clone          PC=0x7f0e03aa102b, FP=0x7f0dff41ffb8 [/lib64/libc.so.6]
Thread 1.4:
>  0 __epoll_wait_nocancel PC=0x7f0e03aa1603, FP=0x7f0e0085ee00 [/lib64/libc.so.6]
   1 epoll_dispatch   PC=0x7f0e053e27b5, FP=0x7f0e0085ee80 [/home/jdelsign/tvbld/linux-x86-64/microway3/totalview.develop/3rdparty/libevent/LIBEvent/epoll.c#465]
   2 event_base_loop  PC=0x7f0e053d2034, FP=0x7f0e0085eee0 [/home/jdelsign/tvbld/linux-x86-64/microway3/totalview.develop/3rdparty/libevent/LIBEvent/event.c#1998]
   3 progress_engine  PC=0x7f0e058e5122, FP=0x7f0e0085ef10 [/home/jdelsign/tvbld/linux-x86-64/microway3/totalview.develop/3rdparty/openpmix/OpenPMIx/src/runtime/pmix_progress_threads.c#232]
   4 start_thread     PC=0x7f0e03d77dce, FP=0x7f0e0085efb0 [/lib64/libpthread.so.0]
   5 __clone          PC=0x7f0e03aa102b, FP=0x7f0e0085efb8 [/lib64/libc.so.6]
d1.<> 
```

**Comment by jjhursey** [comment]
* I'll look into the autogen issue. I thought I fixed that, but maybe I lost the patch.
 * Having both a C and C++ version that essentially do the same things seems problematic. Only one will get exercised, and bug reporters will have to report which one they are using. They would get out of sync.
 * For documentation, I moved it to the README.md at the top level directory to make it easier to find. I'll add the totalview example and notes from that comment.
 * For the last bug that you found, this is something that was fixed with a newer version of PMIx (commit below) to access the launcher namespace. I'll add some protection here, and see if I can add the old method for accessing that information.
  - https://github.com/openpmix/openpmix/issues/1801#issuecomment-648365247

**Comment by jdelsign** [comment]
The point of having the comment in the code is that a debugger **user** will not be reading the README.md file for the shim. Instead, they will see the mpir.c* source file displayed in the debugger, and the comment in the shim code tells them what to do next.

The reason I wrote the shim in the first place was to act as a bridge between existing tools that support MPIR but do not yet support PMIx. TotalView will depend on the shim for at least the initial version of OMPI v5. It was never intended to serve as PMIx how-to sample code.

A month or so ago I went through the trouble of integrating the MPIR-shim, OpenPMIx, libevent, and libhwloc into the TotalView distribution so that users can use the shim when OMPI 5 comes out. These changes probably break that for me. The only useful end-user functional change I see here is support for attach, though I'm not sure if/how that works yet.

Sorry, but these changes are a disincentive for me to merge them back into TotalView's copy of the shim.

**Comment by jjhursey** [comment]
That's a good point about the view of the source file from the debugger. I'll add that back in.

I was also noodling a bit more about Ralph's C++ vs C comment. The C++ version has been verified by you and others and the C version is new. We could have them live side-by-side. The idea would be to keep the C++ version as it is now as the `mpir` binary. This new C version with the library would be installed with it but the binary would be named something like `mpirc`. Then it would be easy to see which version a user is using when they submit a bug, and users of the MPIR Shim would be able to choose the one they want at runtime. I might be able to make a configure switch so that users can pick one or the other or both, but I'm not sure how complex that would get.

The advantage I see of keeping the C++ here (and maintaining both the C and C++ version moving forward) is two fold:
 1. Folks have already validated and integrated the C++ code. Doing that again, possibly late in the release cycle is highly disruptive.
 2. The C++ code, just like the C code, provides a good example of how a tool might use the PMIx interface directly either from C or C++. So if a tool is developed in C++ they would reference the C++ shim for how to make that transition. Same if they come from C. In the future maybe we see if we can add a Python version.

What do you all think?

**Comment by jdelsign** [comment]
The shim was intended to serve a very specific purpose: Compensate for the fact that OMPI v5 is dropping MPIR support. I don't think the shim needs to be _like_ the debugger examples. In fact, the shim was partially constructed using various pieces the existing debugger examples. If there are bugs or functionality missing from the current shim, then they should get fixed. But for me, the wholesale rewrite of the shim to make it useful and more like the debugger examples is simply disruptive and not at all helpful, because TotalView plans to use it in production environments.

**Comment by jjhursey** [comment]
The pushed a couple of commits that address:
 * `autogen.pl` warnings
 * Restore `mpir.cxx` as the `mpir` binary. Rename the C version to `mpirc`.
 * Comment before `main` for debugger users
 * Add protection for missing launcher namespace. Currently a fatal error.

We will plan on discussing this PR on the weekly teleconf this Thursday. I'll put it on the agenda.

We have been discussing the effort of moving to a C version with a shared library in the teleconf for the past few months with general agreement from the developers on the calls about this effort. The PR was posted last week and was discussed last Thursday. If the feeling of the community has changed then we can adapt accordingly.

**Comment by rhc54** [comment]
To be fair, I was under the (apparently incorrect) impression that we were talking in the meetings about _adding_ the C version as opposed to _replacing_ the C++ one. I believe that @jjhursey has modified this PR to fit that understanding.

I guess the question for @jdelsign is: does the presence of the C version cause you difficulties, assuming you can choose which version to configure/build? If so, then would moving the C version into a separate branch be sufficient separation? Or do we need to move it to a completely separate repo?

**Comment by jdelsign** [comment]
> To be fair, I was under the (apparently incorrect) impression that we were talking in the meetings about _adding_ the C version as opposed to _replacing_ the C++ one. I believe that @jjhursey has modified this PR to fit that understanding.

I don't understand the objective here. Why does anyone need an MPIR-shim written in C?

Is it because someone plans to use the shim and they don't have a C++ compiler handy? I doubt it, since C++ compilers are pretty common these days. It does eliminate the dependency on a C++ runtime library making deployment easier, but is that a real concern these days?

I gather from Josh's comments that it was rewritten in C to: (a) be more like the prrte debugger examples, and (b) serve as an example of how a debugger might use PMIx. If that the goal, then maybe the C version belongs in prrte debugger examples.

FWIW, I originally wrote the shim in C++ (not C) for two reasons:
* I found calling into PMIx using C to be extremely error prone and hard to read. The C++ wrappers made it easier to read and harder to make silly mistakes.
* I plan to integrate the shim logic into TotalView someday and TotalView is written in C++, so writing the shim in C++ made sense to me.

> I guess the question for @jdelsign is: does the presence of the C version cause you difficulties, assuming you can choose which version to configure/build?

I'm not sure if the presence of the C version will cause me difficulties, though AFAICT it wouldn't gain anything from merging it into TotalView's copy of the shim. I might be better off picking and choosing changes that I need rather than doing another merge. I don't know yet.

> If so, then would moving the C version into a separate branch be sufficient separation? Or do we need to move it to a completely separate repo?

A separate branch or repro would be fine with me, but again, what's the objective? If it's there to serve as an example, then doesn't it belong with the prrte debugger example? Or, is the intention to make it available to PMIx/OMPI community? If so, then why not fold the MPIR-shim functionality into prun/mpirun, which would eliminate the need for a separate MPIR-shim program, which is what I have wanted all along.

**Comment by rhc54** [comment]
After giving this some consideration and discussing it with @jjhursey, I think the best path forward is to move the C version over to a separate repository. The purpose of the C version is to provide a transition path (via a shared library) for those needing to support an MPIR-based tool during their move to PMIx, but to do it in a form that is more familiar to those working with the PMIx code base.

There is no intention of ever adding the shim code to PMIx as it is too MPI-specific and rather fragile. - I think @jjhursey has a patch or two that address the problems. So no interest or intent in that direction.

Moving the C version to a separate repo keeps this repo "clean" for your use with TotalView. I've asked @jjhursey to post any identified problems as issues here, and if/where IBM has fixes, to please post those as PRs or include suggestions in the issues (since their fixes would likely be in the corresponding C version). @jjhursey noted that the C++ code in mpir-shim appears to need some minor updates to work with the PMIx master branch.

@jjhursey will be creating the new repo shortly, so I'll close out this PR.

**Comment by jjhursey** [comment]
I created a new repo and merged this PR into it
 * https://github.com/openpmix/mpir-to-pmix-guide

That repo will take on the broader role of collecting resources to aid tools in transiting from the MPIR interface to the PMIx tools interface (e.g., presentations, diagrams, other example codes). That will include a link to this repo for the production C++ version of the MPIR Shim.

I'll work on reviewing the delta between the fixes we put in the C version that should be ported to the C++ version and post PRs.

**Pull request closed without merging**
